### ISSUE TITLE
[Bug] Dead for touch area above popup menu

### ISSUE THREAD

**Issue by macieksmola** [RedBanHammer/CometPublic#1]
![image](https://cloud.githubusercontent.com/assets/16581149/12165906/f81477e0-b521-11e5-8d73-5f994a83215d.jpg)
Touching anywhere outside should close the menu, now there is a place above that menu not responding to touch

**Comment by DominicMajor** [comment]
I get this on iOS 9 too

**Comment by RedBanHammer** [comment]
Fixed 6f487be.
