### ISSUE TITLE
[Bug] Fullscreen scrolling behaviour

### ISSUE THREAD

**Issue by macieksmola** [RedBanHammer/CometPublic#2]
Recent changes made it to be more like Safari behaviou but there are still some things to improve.
Safari does that:
1. No bars reveal with fast scrolling until the finger is lifted off the screen
2. Starting to scroll down with bars revealed hides them. Without releasing touch and after swiping up, it behave like the finger was just put on the screen - touch release is needed to reveal bars.

ATM Comet is not doing #2 thing right. It reveals bars after tiny bit of scrolling up (like in previous betas) if touch started with bars revealed.

**Comment by RedBanHammer** [comment]
Bar revealing by scrolling quickly upwards is something deliberate, as Safari's bar behavior makes it too difficult to undo hiding bars. I changed the hiding behavior to collapse if partially retraced (as opposed to expanding) in a5c6230.
