### ISSUE TITLE
[Bug] Soundcloud media player scaling incorrect (way too big)

### ISSUE THREAD

**Issue by DominicMajor** [RedBanHammer/CometPublic#4]
When opening a soundcloud link the media player loads but is far too big. I can scroll around to see all parts but none of the buttons are functional.

![img_0145](https://cloud.githubusercontent.com/assets/8768085/12180103/907325ae-b572-11e5-92cc-1c24e7774613.PNG)

**Comment by RedBanHammer** [comment]
What version of iOS are you running? Is this on a 6?

**Comment by DominicMajor** [comment]
I'm running 9.0.2 on a 6+

**Comment by RedBanHammer** [comment]
[Issue only occurs from subreddit feeds (small thumbnails)]
